//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUUGARUSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLURUNLER()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int KITAPID { get; set; }
        public string KITAPAD { get; set; }
        public Nullable<short> KITAPKATEGORI { get; set; }
        public string YAZAR { get; set; }
        public string KITAPTUR { get; set; }
        public Nullable<decimal> ALISFİYATGRV { get; set; }
        public Nullable<decimal> KURGRV { get; set; }
        public Nullable<decimal> SATISFİYATTL { get; set; }
        public string DURUMU { get; set; }
        public string STOK { get; set; }
        public Nullable<System.DateTime> ALISTARIH { get; set; }
        public Nullable<System.DateTime> SATISTARIH { get; set; }
        public Nullable<decimal> KALANKARTL { get; set; }
    
        public virtual TBLKATEGORILER TBLKATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
